### ISSUE TITLE
Recursive context inclusion in /nexus/core/resource/v0.1.0

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus-kg#189]
I got the following error when trying to play with an instance using the [json-ld playground](https://json-ld.org/playground/). /nexus/core/resource/v0.1.0 can't refer to itself.

```json
{
  "stack": "Error\n    at new JsonLdError (https://cdnjs.cloudflare.com/ajax/libs/jsonld/0.4.2/jsonld.js:2358:19)\n    at https://cdnjs.cloudflare.com/ajax/libs/jsonld/0.4.2/jsonld.js:6714:19\n    at retrieve (https://cdnjs.cloudflare.com/ajax/libs/jsonld/0.4.2/jsonld.js:6793:8)\n    at done (https://cdnjs.cloudflare.com/ajax/libs/jsonld/0.4.2/jsonld.js:6778:11)\n    at <anonymous>",
  "name": "jsonld.ContextUrlError",
  "message": "Cyclical @context URLs detected.",
  "details": {
    "code": "recursive context inclusion",
    "url": "{{base}}/dev/v0/contexts/nexus/core/resource/v0.1.0"
  }
}
```

**Comment by MFSY** [comment]
duplicate of #164
