### ISSUE TITLE
RDFParseException when uploading contexts

### ISSUE THREAD

**Issue by olinux** [BlueBrain/nexus-kg#263]
When I'm uploading the contexts "standard in v0.1.0" and "resource in v0.1.0" from nexus-commons on a empty nexus instance (0.9.3), I get the following exception:

```
kg_1       | Response: 'INSERT-WITH-BODY: baseURI=http://172.18.2.71:9999/blazegraph/namespace/kg/sparql, Content-Type=application/ld+json, context-uri=[https://nexus-dev.humanbrainproject.org/v0/contexts/graphs/contexts/nexus/core/resource/v0.1.0]
kg_1       | java.util.concurrent.ExecutionException: org.openrdf.rio.RDFParseException: Could not parse JSONLD
kg_1       | 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
kg_1       | 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
kg_1       | 	at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:286)
kg_1       | 	at com.bigdata.rdf.sail.webapp.InsertServlet.doPostWithBody(InsertServlet.java:206)
kg_1       | 	at com.bigdata.rdf.sail.webapp.InsertServlet.doPost(InsertServlet.java:122)
kg_1       | 	at com.bigdata.rdf.sail.webapp.RESTServlet.doPost(RESTServlet.java:308)
kg_1       | 	at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doPost(MultiTenancyServlet.java:193)
kg_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
kg_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
kg_1       | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
kg_1       | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
kg_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
kg_1       | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
kg_1       | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
kg_1       | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
kg_1       | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
kg_1       | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
kg_1       | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
kg_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
kg_1       | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
kg_1       | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
kg_1       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
kg_1       | 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
kg_1       | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
kg_1       | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
kg_1       | 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
kg_1       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
kg_1       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
kg_1       | 	at java.lang.Thread.run(Thread.java:748)
kg_1       | Caused by: org.openrdf.rio.RDFParseException: Could not parse JSONLD
kg_1       | 	at com.github.jsonldjava.sesame.SesameJSONLDParser.parse(SesameJSONLDParser.java:67)
kg_1       | 	at com.bigdata.rdf.sail.webapp.InsertServlet$InsertWithBodyTask.call(InsertServlet.java:308)
kg_1       | 	at com.bigdata.rdf.sail.webapp.InsertServlet$InsertWithBodyTask.call(InsertServlet.java:229)
kg_1       | 	at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:68)
kg_1       | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
kg_1       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
kg_1       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
kg_1       | 	... 1 more
kg_1       | Caused by: com.github.jsonldjava.core.JsonLdError: invalid remote context: https://nexus-dev.humanbrainproject.org/v0/contexts/nexus/core/standards/v0.1.0
kg_1       | 	at com.github.jsonldjava.core.Context.parse(Context.java:174)
kg_1       | 	at com.github.jsonldjava.core.Context.parse(Context.java:251)
kg_1       | 	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:533)
kg_1       | 	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:980)
kg_1       | 	at com.github.jsonldjava.core.JsonLdProcessor.expand(JsonLdProcessor.java:137)
kg_1       | 	at com.github.jsonldjava.core.JsonLdProcessor.toRDF(JsonLdProcessor.java:472)
kg_1       | 	at com.github.jsonldjava.sesame.SesameJSONLDParser.parse(SesameJSONLDParser.java:65)
kg_1       | 	... 7 more
```

The standards/v0.1.0 context is visible from both, blazegraph and the nexus rest API.

**Comment by olinux** [comment]
I figured it out: Our upload script messed up the order of the uploads - so the resource context has been tried to be uploaded before the standard and therefore was not able to resolve it - so it's a correct behavior.

**Comment by olinux** [comment]
The logs were delayed - it still happens even with the right order.

**Comment by umbreak** [comment]
Context does not get resolved in `ContextSparqlIndexer` before sending it to Blazegraph. We have to resolve it first.

**Comment by olinux** [comment]
To make things worse, the exception causes a never ending InsertWithBodyTask query on blazegraph simliar to the delete issue in #262. A restart of blazegraph helps (it's currently the only known trigger for this behaviour) - but should probably be solved in a similar way as the delete (either by fixing blazegraph or by using a different insert mechanism)

**Comment by bogdanromanx** [comment]
I'm on it; I'm switching KG to use the sparql endpoint instead which should resolve long running InsertWithBodyTask also.

**Comment by olinux** [comment]
Works with 0.9.8
